import re
from sqlalchemy import create_engine, text, inspect
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import SQLAlchemyError
import pandas as pd
from typing import List, Dict, Any, Optional, Tuple
from config.config import Config


class MySQLService:
    def __init__(self):
        self.connection_string = (
            f"mysql+mysqlconnector://"
            f"{Config.MYSQL_USER}:{Config.MYSQL_PASSWORD}"
            f"@{Config.MYSQL_HOST}:{Config.MYSQL_PORT}"
            f"/{Config.MYSQL_DATABASE}"
        )
        self.engine = None
        self.Session = None
        self.connect()

    def connect(self):
        try:
            self.engine = create_engine(
                self.connection_string,
                pool_pre_ping=True,
                echo=False,
                pool_recycle=3600,
                pool_size=5,
                max_overflow=10
            )
            self.Session = sessionmaker(bind=self.engine)
            with self.engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            print("Connected to MySQL database")
        except SQLAlchemyError as e:
            print(f"Connection error: {e}")
            raise

    def get_database_schema(self) -> str:
        """Fetches the schema so the AI knows exact table and column names."""
        try:
            inspector = inspect(self.engine)
            schema_info = []
            
            all_tables = inspector.get_table_names()
            # We focus on the first 20 tables to keep the prompt size manageable
            tables = all_tables[:20]  
            
            for table_name in tables:
                columns = inspector.get_columns(table_name)
                table_schema = f"Table: {table_name}\nColumns:\n"
                
                for col in columns:
                    col_def = f"  - {col['name']} ({str(col['type'])})"
                    if not col['nullable']:
                        col_def += " NOT NULL"
                    table_schema += col_def + "\n"
                
                schema_info.append(table_schema)
            
            return "\n\n".join(schema_info)
        except SQLAlchemyError as e:
            print(f"Schema extraction error: {e}")
            return ""

    def execute_query(self, query: str) -> Tuple[Optional[List[Dict]], Optional[str]]:
        """Used for SELECT queries generated by the AI."""
        query_upper = query.upper().strip()
        
        # Strict read-only check for AI-generated queries
        if not query_upper.startswith(("SELECT", "WITH")):
            return None, "Only SELECT queries are allowed through this method."
        
        forbidden = ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE"]
        for keyword in forbidden:
            if f" {keyword} " in f" {query_upper} ":
                return None, f"Query contains forbidden keyword: {keyword}"
        
        try:
            with self.engine.connect() as conn:
                result = conn.execute(text(query))
                # Convert ResultProxy to list of dicts
                formatted_results = [dict(row._mapping) for row in result]
                return formatted_results, None
        except SQLAlchemyError as e:
            return None, f"SQL Error: {str(e)[:200]}"

    def execute_update(self, query: str) -> Tuple[bool, Optional[str]]:
        """
        Specialized method to allow UPDATE/INSERT/DELETE.
        Used by OrderServiceAgent for specific actions like 'Cancel Order'.
        """
        try:
            with self.engine.connect() as conn:
                conn.execute(text(query))
                conn.commit()  # Crucial for MySQL to save changes
                return True, None
        except SQLAlchemyError as e:
            error_msg = f"Update Error: {str(e)[:200]}"
            print(error_msg)
            return False, error_msg

    def test_connection(self) -> bool:
        try:
            with self.engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            return True
        except SQLAlchemyError:
            return False

    def close(self):
        if self.engine:
            self.engine.dispose()